database = {
    'd07_magnuson2018_30348759': {
        'experiment': {
            'species': 'human',
            'tissue': 'colon',
            'disease': 'cancer',
            'celltype': 'tregs',
            'celltype_definition': '',
            'design': '',
            'nsamples': '6 patients with healthy and tumor tissue + few more unmatched',
        },
        'assay': {
            'type': 'bulk_sorted',
            'platform': 'rnaseq',
            'ncells': '',
        },
        'files': {
            'raw': {
                'counts': 'GSE116347_Gene_count_table_human.csv',
                'meta': 'column header of files_raw expr_counts',
                'source': 'https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE116347',
            },
            'processed': {
                'counts': '',
                'normalized': '',
                'meta': '',
                'scrnaseq_obj': '',
                'source': '',
                'qc': '',
            },
            'reprocessed': {
                'counts': '',
                'normalized': '',
                'meta': '',
                'scrnaseq_obj': '',
                'source': '',
                'qc': '',
            },
        },
        'manuscript': {
            'info': 'Magnuson et al. Identification and validation of a tumor-infiltrating Treg transcriptional signature conserved across species and tumor types. Proc Natl Acad Sci U S A. 2018.',
            'doi': 'DOI: 10.1073/pnas.1810580115',
            'url_supplementary_data': '',
        },
    },
    'd06_elmentaite2021_34497389': {
        'experiment': {
            'species': 'human',
            'tissue': 'intestinal',
            'disease': 'healthy',
            'celltype': 'unsorted',
            'celltype_definition': '',
            'design': 'Human adult tissue was obtained by the Cambridge Biorepository of Translational Medicine from deceased transplant organ donors...',
            'nsamples': '0',
        },
        'assay': {
            'type': 'scrnaseq(10x)',
            'platform': '',
            'ncells': '',
        },
        'files': {
            'raw': {
                'counts': '',
                'meta': '',
                'source': '',
            },
            'processed': {
                'counts': '',
                'normalized': '',
                'meta': '',
                'scrnaseq_obj': '',
                'source': '',
                'qc': '',
            },
            'reprocessed': {
                'counts': '',
                'normalized': '',
                'meta': '',
                'scrnaseq_obj': '',
                'source': '',
                'qc': '',
            },
        },
        'manuscript': {
            'info': 'https://www.nature.com/articles/s41586-021-03852-1 Full single-cell RNA-seq dataset of 428K intestinal cells from fetal, pediatric, adult donors, and up to 11 intestinal regions.',
            'doi': '',
            'url_supplementary_data': 'https://cellgeni.cog.sanger.ac.uk/gutcellatlas/Tcell_log_counts02_v2.h5ad',
        },
    },
    'd05_plitas2016_27851913': {
        'experiment': {
            'species': 'human',
            'tissue': 'primary_brca, healthy_breast_tissue',
            'disease': 'tumor_brca',
            'celltype': 'Tregs',
            'celltype_definition': '',
            'design': '',
            'nsamples': '',
        },
        'assay': {
            'type': 'bulk_rnaseq',
            'platform': '',
            'ncells': '',
        },
        'files': {
            'raw': {
                'counts': 'https://ftp.ncbi.nlm.nih.gov/geo/series/GSE89nnn/GSE89225/suppl/GSE89225%5FIllumina%5Fcounts.csv.gz',
                'meta': 'https://ftp.ncbi.nlm.nih.gov/geo/series/GSE89nnn/GSE89225/matrix/GSE89225-GPL16791_series_matrix.txt.gz',
                'source': '',
            },
            'processed': {
                'counts': '',
                'normalized': '',
                'meta': '',
                'scrnaseq_obj': '',
                'source': '',
                'qc': '',
            },
            'reprocessed': {
                'counts': '',
                'normalized': '',
                'meta': '',
                'scrnaseq_obj': '',
                'source': '',
                'qc': '',
            },
        },
        'manuscript': {
            'info': 'Regulatory T Cells Exhibit Distinct Features in Human Breast Cancer Immunity 2016',
            'doi': '',
            'url_supplementary_data': '',
        },
    },
    'd04_tabulasampies_35549404': {
        'experiment': {
            'species': 'human',
            'tissue': 'multiple',
            'disease': 'normal',
            'celltype': 'multiple',
            'celltype_definition': '',
            'design': '',
            'nsamples': '',
        },
        'assay': {
            'type': 'scrnaseq',
            'platform': '',
            'ncells': '',
        },
        'files': {
            'raw': {
                'counts': '',
                'meta': '',
                'source': '',
            },
            'processed': {
                'counts': '',
                'normalized': '',
                'meta': '',
                'scrnaseq_obj': '',
                'source': '',
                'qc': '',
            },
            'reprocessed': {
                'counts': '',
                'normalized': '',
                'meta': '',
                'scrnaseq_obj': '',
                'source': '',
                'qc': '',
            },
        },
        'manuscript': {
            'info': 'The Tabula Sapiens: A multiple-organ, single-cell transcriptomic atlas of humans. Science 2022 500,000 cells from 24 different tissues and organs, many from the same donor.',
            'doi': '',
            'url_supplementary_data': '',
        },
    },
    'd03_yang2024_39047727': {
        'experiment': {
            'species': 'human',
            'tissue': 'multiple',
            'disease': 'cancer',
            'celltype': 'B cells',
            'celltype_definition': '',
            'design': '',
            'nsamples': '',
        },
        'assay': {
            'type': 'scrnaseq',
            'platform': '',
            'ncells': '',
        },
        'files': {
            'raw': {
                'counts': '',
                'meta': '',
                'source': '',
            },
            'processed': {
                'counts': '',
                'normalized': '',
                'meta': '',
                'scrnaseq_obj': '',
                'source': '',
                'qc': '',
            },
            'reprocessed': {
                'counts': '',
                'normalized': '',
                'meta': '',
                'scrnaseq_obj': '',
                'source': '',
                'qc': '',
            },
        },
        'manuscript': {
            'info': 'B cell atlas from tumor: Pan-cancer single-cell dissection reveals phenotypically distinct B cell subtypes. Cell 2024 DOI: 10.1016/j.cell.2024.06.038',
            'doi': '',
            'url_supplementary_data': '',
        },
    },
    'd02_miragaia2019_30737144': {
        'experiment': {
            'species': 'human',
            'tissue': 'colon',
            'disease': 'normal',
            'celltype': 'Regulatory T cells',
            'celltype_definition': '',
            'design': '',
            'nsamples': '',
        },
        'assay': {
            'type': 'scrnaseq',
            'platform': 'ss2',
            'ncells': '',
        },
        'files': {
            'raw': {
                'counts': '',
                'meta': '',
                'source': '',
            },
            'processed': {
                'counts': '',
                'normalized': '',
                'meta': '',
                'scrnaseq_obj': '',
                'source': '',
                'qc': '',
            },
            'reprocessed': {
                'counts': '',
                'normalized': '',
                'meta': '',
                'scrnaseq_obj': '',
                'source': '',
                'qc': '',
            },
        },
        'manuscript': {
            'info': 'Single-Cell Transcriptomics of Regulatory T Cells Reveals Trajectories of Tissue Adaptation. Immunity 2019 DOI: 10.1016/j.immuni.2019.01.001',
            'doi': '',
            'url_supplementary_data': '',
        },
    },
    'd01_zheng2019_34914499': {
        'experiment': {
            'species': 'human',
            'tissue': 'multiple',
            'disease': 'cancer',
            'celltype': 'T cells',
            'celltype_definition': '',
            'design': '',
            'nsamples': '',
        },
        'assay': {
            'type': 'scrnaseq',
            'platform': '',
            'ncells': '',
        },
        'files': {
             'raw': {
                'counts': '',
                'meta': '',
                'source': '',
            },
            'processed': {
                'counts': '',
                'normalized': '',
                'meta': '',
                'scrnaseq_obj': '',
                'source': '',
                'qc': '',
            },
            'reprocessed': {
                'counts': '',
                'normalized': '',
                'meta': '',
                'scrnaseq_obj': '',
                'source': '',
                'qc': '',
            },
        },
        'manuscript': {
            'info': 'Link to manuscript: https://example.com/zheng2019',
            'doi': '',
            'url_supplementary_data': '',
        },
    },
}
